### ISSUE TITLE
Warning Annotation Regarding Nod.js 16 Deprecated

### ISSUE THREAD

**Issue by StephenShamakian** [oras-project/setup-oras#26]
Every Action workflow we use this in were getting warnings annotations with every run that this action is using a deprecated version of Node.js (v16).

Is these a version we can use that doesn't have this issue?

**Comment by StephenShamakian** [comment]
Yeah I saw that too... As a workaround I'm using the 'main' branch vs. a tagged release. But this is less than Ideal.

**Comment by shizhMSFT** [comment]
We are releasing a new version of oras CLI recently and will have a new release of the `oras-setup` action. /cc @FeynmanZhou

**Comment by shizhMSFT** [comment]
@StephenShamakian @BethGriggs New version `1.2.0` of `setup-oras` was just [released](https://github.com/oras-project/setup-oras/releases/tag/v1.2.0)!
