### ISSUE TITLE
Cut the first release and publish it to GH marketplace

### ISSUE THREAD

**Issue by FeynmanZhou** [oras-project/setup-oras#8]
According to https://github.com/oras-project/oras/issues/744, the first phase of development is finished and ORAS v1.0.0 is available on Mar 20, now it's ready to cut the first release for this GH actions and publish to the GH marketplace.

**Comment by shizhMSFT** [comment]
Released [v1.0.0](https://github.com/oras-project/setup-oras/releases/tag/v1.0.0) and published to [market place](https://github.com/marketplace/actions/setup-oras).
